ALTER TABLE traces
    ADD COLUMN IF NOT EXISTS request_headers_ref TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS response_headers_ref TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS usage_prompt_tokens INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS usage_completion_tokens INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS usage_total_tokens INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS usage_reasoning_tokens INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS usage_cached_tokens INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS estimated_cost TEXT NOT NULL DEFAULT '';
